# Cloudflare Worker — MandiMind API

name = "mandimind-api"
main = "src/worker-live.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
tsconfig = "tsconfig.worker.json"

[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "MANDIMIND_CACHE"
id = "a9a67d4d453a42c694998a232d6d03e4"

[observability]
enabled = true
